source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'

target "HttpCommunication" do
	pod 'Hydra', :path => '~/Workspace/OpenSources/Hydra'
	pod 'HJAsyncHttpDeliverer', :path => '~/Workspace/OpenSources/HJAsyncHttpDeliverer'
end
